networks:
  2024_summer_coding:
    name: 2024_summer_coding_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
    labels:
      com.docker.compose.network: '2024_summer_coding'
      com.docker.compose.project: '2024_summer_coding'
    external: false


services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb 
    environment:
      MYSQL_ROOT_PASSWORD: '=dl-13579' 
      MYSQL_DATABASE: '2024_summer_coding'
    volumes:
      - ../mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - 2024_summer_coding

  springboot:
    image: springboot:latest
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/2024_summer_coding?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: =dl-13579
      SPRING__PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    networks:
      - 2024_summer_coding
    depends_on:
      - mysqldb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../prometheus-data:/prometheus
      - ../prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - 2024_summer_coding
    depends_on:
      - springboot

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ../grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - 2024_summer_coding
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - 2024_summer_coding  
    depends_on:
      - springboot  